<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class)
    ->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
</div></div></div>
<div class="topbaner01">
	<div class="bnrtxt">
    	<h3>India’s only online store for Vintage Furniture</h3>
        <img src="<?php echo $mediaUrl; ?>images/barerdown01.png"/>
    </div>
	<img src="<?php echo $mediaUrl; ?>images/banner01.jpg"/>
    <div class="bnrtxtbot"><img src="<?php echo $mediaUrl; ?>images/arrowdown.png"/></div>
</div>

<div class="section02">
	<div class="container1">
    	<div class="section02left">
        	<h3>CREATING DREAM HOME FOR YOU!</h3>
            <p>Curves and Carving introduces India’s first fine living platform where you have a choice of getting your home designed in Vintage, Colonial and Traditional interior style. We look to create the marvelous grandeur of royal living for your abode.</p>
			<p>We have empanelled well known Interior Designer in your cities and nearby, and helped them with nuances of creating a classical living interiors. If you are looking for someone to create an amazing fine living experience, your search ends here.</p>
            <p><a href="#">read more</a> <a href="#">play video <i class="fa fa-play"></i></a></p>
        </div>
        <div class="section02rigt"><img src="<?php echo $mediaUrl; ?>images/chair.png"/></div>
    </div>
</div>

<div class="section03">
	<div class="container1">
    	<div class="section03rigt">
        	<h3>FASHIONABLE FURNITURE THAT SPEAKS FOR ITSELF</h3>
            <p>Curves and Carving introduces India’s first fine living platform where you have a choice of getting your home designed in Vintage, Colonial and Traditional interior style. We look to create the marvelous grandeur of royal living for your abode.</p>
			<p>We have empanelled well known Interior Designer in your cities and nearby, and helped them with nuances of creating a classical living interiors. If you are looking for someone to create an amazing fine living experience, your search ends here.</p>
            <p><a href="#">read more</a></p>
        </div>
    </div>
</div>

<!--<div class="section04">
	<div class="container1">
    	<div class="section04img"><img src="<?php echo $mediaUrl; ?>images/product.jpg"/></div>
    </div>
</div>-->

<div class="section05 section04">
	<div class="container1">
    	<div class="galleryhed01">
        	<h3>Your Dreams<br />Antiques</h3>
            <div class="tabbing">
                <ul class="tabNav">
                    <li><a href="#producttab1">Chest of Drawers</a></li>
                    <li><a href="#producttab2">Center Tables</a></li>
                    <li><a href="#producttab3">Study Tables</a></li>
                </ul>
                <div class="tabContainer">
                    <div class="tabContent" id="producttab1">
					<?php
					$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
					$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
					$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
					$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
					$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
					$categoryId = 62;
					$category = $categoryFactory->create()->load($categoryId);
					$categoryProducts = $category->getProductCollection()->addAttributeToSelect('*')->setPageSize(9);
					foreach ($categoryProducts as $product) 
					{
					$imagewidth=350;
					$imageheight=350;
					$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
					$imageUrl = $imageHelper->init($product, 'product_page_image_small')->setImageFile($product->getFile())->resize($imagewidth, $imageheight)->getUrl();
					 //echo $imageUrl;
					?>
                        <div class="productbox">
						<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							  $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
							  $addToCartUrl =  $listBlock->getAddToCartUrl($product); ?>
                        	<div class="productboximg">
                            	<img src="<?= $imageUrl;?>" alt="<?= $product->getName(); ?>" />
                                <h4> <a href="<?= $product->getProductUrl(); ?>"><?= $product->getName(); ?></a></h4>
                            </div>
                            <div class="productboxtxt">
                            	<div class="proprice01">
                                	<p><del>Rs. <?= number_format($product->getPrice()); ?></del>Rs. <?= number_format($product->getFinalPrice(),2); ?></p>
                                </div>
                                <div class="proadtocrt">
								<div class="prowish">
								<a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product) ?>' class="action towishlist" data-action="add-to-wishlist"><i class="fa fa-heart"></i>
								</a>
                                	</div>
									<div class="proadto"><a href="<?= $product->getProductUrl(); ?>">Add to cart</a></div>
                                </div>
                            </div>
                        </div>
						<?php } ?> 
                    </div>
					<div class="tabContent" id="producttab2">
					<?php
					$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
					$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
					$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
					$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
					$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
					$categoryId = 66;
					$category = $categoryFactory->create()->load($categoryId);
					$categoryProducts = $category->getProductCollection()->addAttributeToSelect('*')->setPageSize(9);
					foreach ($categoryProducts as $product) 
					{
					$imagewidth=350;
					$imageheight=350;
					$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
					$imageUrl = $imageHelper->init($product, 'product_page_image_small')->setImageFile($product->getFile())->resize($imagewidth, $imageheight)->getUrl();
					 //echo $imageUrl;
					?>
                        <div class="productbox">
						<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							  $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
							  $addToCartUrl =  $listBlock->getAddToCartUrl($product); ?>
                        	<div class="productboximg">
                            	<img src="<?= $imageUrl;?>" alt="<?= $product->getName(); ?>" />
                                <h4> <a href="<?= $product->getProductUrl(); ?>"><?= $product->getName(); ?></a></h4>
                            </div>
                            <div class="productboxtxt">
                            	<div class="proprice01">
                                	<p><del>Rs. <?= number_format($product->getPrice()); ?></del>Rs. <?= number_format($product->getFinalPrice(),2); ?></p>
                                </div>
                                <div class="proadtocrt">
                                	<div class="prowish"><a href="#"><i class="fa fa-heart"></i></a></div>
									<div class="proadto"><a href="<?= $product->getProductUrl(); ?>">Add to cart</a></div>
                                </div>
                            </div>
                        </div>
						<?php } ?> 
                    </div>
					<div class="tabContent" id="producttab3">
					<?php
					$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
					$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
					$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
					$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
					$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
					$categoryId = 67;
					$category = $categoryFactory->create()->load($categoryId);
					$categoryProducts = $category->getProductCollection()->addAttributeToSelect('*')->setPageSize(9);
					foreach ($categoryProducts as $product) 
					{
					$imagewidth=350;
					$imageheight=350;
					$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
					$imageUrl = $imageHelper->init($product, 'product_page_image_small')->setImageFile($product->getFile())->resize($imagewidth, $imageheight)->getUrl();
					 //echo $imageUrl;
					?>
                        <div class="productbox">
						<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							  $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
							  $addToCartUrl =  $listBlock->getAddToCartUrl($product); ?>
                        	<div class="productboximg">
                            	<img src="<?= $imageUrl;?>" alt="<?= $product->getName(); ?>" />
                                <h4> <a href="<?= $product->getProductUrl(); ?>"><?= $product->getName(); ?></a></h4>
                            </div>
                            <div class="productboxtxt">
                            	<div class="proprice01">
                                	<p><del>Rs. <?= number_format($product->getPrice()); ?></del>Rs. <?= number_format($product->getFinalPrice(),2); ?></p>
                                </div>
                                <div class="proadtocrt">
                                	<div class="prowish"><a href="#"><i class="fa fa-heart"></i></a></div>
									<div class="proadto"><a href="<?= $product->getProductUrl(); ?>">Add to cart</a></div>
                                </div>
                            </div>
                        </div>
						<?php } ?> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section05">
	<div class="container1">
    	<div class="galleryhed01">
        	<h3>Gallery</h3>
            <div class="tabbing">
                <ul class="tabNav">
                    <li><a href="#tab1">COMPLETED</a></li>
                    <li><a href="#tab2">CENTER TABLES</a></li>
                </ul>
                <div class="tabContainer">
                    <div class="tabContent" id="tab1">
                        <div class="galerybox">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('gallery_completed')->toHtml(); ?>
                        </div>
                    </div>
                    <div class="tabContent" id="tab2">
                        <div class="galerybox">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('gallery_table')->toHtml(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section06">
	<div class="container1">
    	<div class="section06lft">
        	<h3>ABOUT US</h3>
            <p>THANK YOU for visiting us again. Your admiration and patronage has led to 2000+ daily visitors on this website. Last 4+ years have seen C&C furniture carve out a niche for itself , taking us to 1500+ homes across India & abroad. Curves & Carvings Furniture is India's ONLY portal to offer customised teak wood designer luxury furniture to customers. We have some of the leading personalities of the country as our customers.</p>

			<p>ONLY portal to offer customised teak wood designer luxury furniture to customers. We have some of the leading personalities of the country as our customers.</p>
            
            <p><a href="#">Read More</a></p>
        </div>
        <div class="section06rigt"><img src="<?php echo $mediaUrl; ?>images/abtvideo01.jpg"/></div>
    </div>
</div>

<div class="section07">
	<div class="container1">
    	<div class="botcall01">
        	<ul>
            	<li>
                	<img src="<?php echo $mediaUrl; ?>images/boticon01.png" />
                    <h3>QUESTIONS</h3>
                    <p>For any questions or clarifications, you can contact us at <br /><a href="mailto:contact@curvesandcarvings.com">contact@curvesandcarvings.com</a> or <br />call at <a href="tel:00917722080791">0091 7722080791</a></p>
                </li>
                <li>
                	<img src="<?php echo $mediaUrl; ?>images/boticon02.png" />
                    <h3>STRESS FREE DELIVERY</h3>
                    <p>"If its broken, it's ours". We deliver your furniture with utmost care.</p>
                </li>
                <li>
                	<img src="<?php echo $mediaUrl; ?>images/boticon03.png" />
                    <h3>PRODUCT CUSTOMISATION</h3>
                    <p>We offer customization of almost everything you want, be it Wood, Polish, Paint or Fabric. You decide
and let us make it for you.</p>
                </li>
                <li>
                	<img src="<?php echo $mediaUrl; ?>images/boticon04.png" />
                    <h3>PRODUCT RANGE</h3>
                    <p>We offer best online collection of Exquisite Designer & Luxury Solid Wood Furniture across categories. We can almost make any design in wood.</p>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="section08">
	<div class="container1">
    	<div class="hometesti01">
        	<h3>What client says</h3>
            <div class="owl-carousel owl-theme testimonial">
            	<div class="item">
                	<div class="hometesti01box">
                    	<img src="<?php echo $mediaUrl; ?>images/testiicon01.png" />
                        <h4>Sunil Desahpande</h4>
                        <h5>Physician, Aurangabad</h5>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
                <div class="item">
                	<div class="hometesti01box">
                    	<img src="<?php echo $mediaUrl; ?>images/testiicon01.png" />
                        <h4>Ajay Vishwakarma</h4>
                        <h5>IBM, Pune</h5>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
                <div class="item">
                	<div class="hometesti01box">
                    	<img src="<?php echo $mediaUrl; ?>images/testiicon01.png" />
                        <h4>Timmy Mehta</h4>
                        <h5>Businessman Andheri, Mumbai</h5>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
                <div class="item">
                	<div class="hometesti01box">
                    	<img src="<?php echo $mediaUrl; ?>images/testiicon01.png" />
                        <h4>Navaid Merchant</h4>
                        <h5>Businessman Byculla, Mumbai</h5>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section09">
	<div class="container1">
    	<div class="homeblog">
        	<h3>Blogs</h3>
            <div class="owl-carousel owl-theme hmblog">
            	<div class="item">
                	<div class="homeblogbox">
                    	<div class="homeblogboximg"><img src="<?php echo $mediaUrl; ?>images/homeblog01.jpg" /></div>
                        <div class="homeblogboxtxt">
                            <h4>Procust Customisation</h4>
                            <p>We offer customization of almost  everything you want, be it Wood, Polish, Paint or Fabric. You decide and let us make it for you. We offer customization of almost everything you want,</p>
                            <p><a href="#">Read More</a></p>
                        </div>
                    </div>
                </div>
                <div class="item">
                	<div class="homeblogbox">
                    	<div class="homeblogboximg"><img src="<?php echo $mediaUrl; ?>images/homeblog02.jpg" /></div>
                        <div class="homeblogboxtxt">
                            <h4>Procust Customisation</h4>
                            <p>We offer customization of almost  everything you want, be it Wood, Polish, Paint or Fabric. You decide and let us make it for you. We offer customization of almost everything you want,</p>
                            <p><a href="#">Read More</a></p>
                        </div>
                    </div>
                </div>
                <div class="item">
                	<div class="homeblogbox">
                    	<div class="homeblogboximg"><img src="<?php echo $mediaUrl; ?>images/homeblog02.jpg" /></div>
                        <div class="homeblogboxtxt">
                            <h4>Procust Customisation</h4>
                            <p>We offer customization of almost  everything you want, be it Wood, Polish, Paint or Fabric. You decide and let us make it for you. We offer customization of almost everything you want,</p>
                            <p><a href="#">Read More</a></p>
                        </div>
                    </div>
                </div>
                <div class="item">
                	<div class="homeblogbox">
                    	<div class="homeblogboximg"><img src="<?php echo $mediaUrl; ?>images/homeblog02.jpg" /></div>
                        <div class="homeblogboxtxt">
                            <h4>Procust Customisation</h4>
                            <p>We offer customization of almost  everything you want, be it Wood, Polish, Paint or Fabric. You decide and let us make it for you. We offer customization of almost everything you want,</p>
                            <p><a href="#">Read More</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section010">
	<div class="container1">
    	<div class="homseco01">
        	<img src="<?php echo $mediaUrl; ?>images/hmeseco.jpg" />
        	<h3>Buy Solid Wood Luxury Furniture Online in India</h3>
            <p>Curves and Carvings is the finest online store for shopping Luxury furniture online in India. We specialize in making hand-crafted designer furniture and luxury furniture. Over the years, we have carefully selected the finest pieces from amongst thousands of Antique designs, Classic & Vintage designs and introduced these into our ever-increasing collection. As a standard practice, we use seasoned Teak wood to make our furniture, however our artists are equally adept in making furniture from other woods like Mahagony or Sheesham.</p>

			<p>We are glad to work closely with our customers to turn your furniture ideas, thoughts and fantasies into reality. Bring us any references, photographs, sketches with dimensions and specifications and we will custom made that piece for you.</p>

			<p>At Curves and Carvings, we are committed to provide widest range of lifestyle luxury furniture and home decor products. As of now, we offer teak wood furniture in Home furniture categories like Bedroom furniture, Living room furniture & Dining room furniture. You can choose and buy online from widest range of Designer Luxury Beds, Designer Luxury Sofa Sets, Designer Luxury Dining Sets, Designer Luxury Display Units, Designer Console Tables, Designer Decorative Mirrors, Designer Luxury Wardrobes, Designer Chest of Drawers, Designer Antique Chairs & Designer Luxury Study Tables. Shortly, we will be entering into designer home decor and furnishing as well.</p>
        </div>
    </div>
</div>











