<div class="gallery_page" > 
<div class="gallery-<?php echo $this->getGallery()->getId(); ?> gallery galerybox" style="height:auto !important;">
    <?php foreach ($block->getImages() as $image): ?>
        <?php echo $block->getImageHtml($image) ?>
    <?php endforeach; ?>
</div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'snapGallery'
    ], function ($) {
        $('.gallery-<?php echo $this->getGallery()->getId(); ?>').snapGallery({
            minWidth: 100,
            maxCols: 4,
            margin: 5
        });
    });
</script>