<?php
/**
 * Copyright 2011 Adobe
 * All Rights Reserved.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Framework\View\Element\ButtonLockManager|null $buttonLockManager */
$buttonLockManager = $block->getData('button_lock_manager');
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>
<form class="form contact contctpagefom"
      action="<?= $escaper->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label">
            <?= $escaper->escapeHtml(__('Curves & Carvings is a registered brand owned and managed by Curves and Carvings Retail. Curves and Carvings Retail is duly registered U.P. based Indian company with GSTIN 09AAMFC8924H1Z1, fulfilling all the statutory and compliance requirement under extant laws and regulations. We are also certified exporter with IEC AAMFC8924H.')) ?>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $escaper->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name"
                       id="name"
                       title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                       value="<?= $escaper->escapeHtmlAttr($viewModel->getUserName()) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                       value="<?= $escaper->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"
                       data-mage-init='{"mage/trim-input":{}}'
                />
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $escaper->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone"
                       id="telephone"
                       title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                       value="<?= $escaper->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                       class="input-text"
                       type="tel" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment">
                <span><?= $escaper->escapeHtml(__('What’s on your mind?')) ?></span>
            </label>
            <div class="control">
                <textarea name="comment"
                          id="comment"
                          title="<?= $escaper->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                          class="input-text"
                          cols="5"
                          rows="3"
                          data-validate="{required:true}"
                ><?= $escaper->escapeHtml($viewModel->getUserComment()) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary"
                    id="send2"
                <?php if ($buttonLockManager?->isDisabled('contact_us_form_submit')): ?>
                    disabled="disabled"
                <?php endif; ?>>
                <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
<div class="contctmap">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15077.442623136998!2d72.829826!3d19.135684!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b7e99255524b%3A0xf81e7faa48cf34f9!2sCurves%20and%20Carvings!5e0!3m2!1sen!2sin!4v1694672067496!5m2!1sen!2sin"
            width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>
<div class="contact_bottom">
    <ul>
        <li><i class="fa fa-map-marker" aria-hidden="true"></i><br><h4><?= $escaper->escapeHtml(__('Branch Addresses')) ?></h4>
            <p><a href="https://goo.gl/maps/CY5TL9XoiLo4s7ek8" target="_blank" rel="noopener"><strong>Mumbai Showroom&nbsp;(closed for&nbsp;relocation)&nbsp;</strong></a>VAV Retail, 23G, Laxmi Industrial Estate, Near Lokhandwala Circle, Andheri (West), Mumbai 400053,&nbsp;Mobile /&nbsp;Whatsapp&nbsp;7722080791&nbsp;</p>
            <p><strong>Saharanpur (U.P) Showroom &amp;&nbsp;Workshop</strong>Plot 395 397, Siddharth Nagar, Chilkana Road, Saharanpur&nbsp;247001</p>
            <p><strong>For Import&nbsp;to UK &amp; Europe</strong>Varun Maini, Mobile / Whatsapp&nbsp;00447472508671</p>
            <p><strong>For Import to Dubai &amp; Middle-East</strong>AL Jannat, Mobile / Whatsapp 00971 501275224, Landline 00971 44272110, Email- admin@aljannat.ae</p>
        </li>
        <li><i class="fa fa-envelope" aria-hidden="true"></i><br><h4><?= $escaper->escapeHtml(__('Email ID')) ?></h4><p><a href="mailto:contact@curvesandcarvings.com">contact@curvesandcarvings.com</a></p></li>
        <li><i class="fa fa-phone-square" aria-hidden="true"></i><br><h4><?= $escaper->escapeHtml(__('Phone')) ?></h4><p><a href="tel:7722080791">7722080791</a></p></li>
        <li><i class="fa fa-bell" aria-hidden="true"></i><br><h4><?= $escaper->escapeHtml(__('Follow us')) ?></h4>
            <div class="social01">
                <a href="https://www.facebook.com/curvesandcarvings" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="https://www.linkedin.com/company/curves-and-carvings" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                <a href="https://in.pinterest.com/CurvesnCarvings/" target="_blank"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="https://twitter.com/curvesncarvings" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </li>
    </ul>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>
