<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 */

$_product = $block->getProduct();
$buttonTitle = __('Add to Cart');
?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <button type="button"
                    title="<?= $block->escapeHtmlAttr(__('Buy Now')) ?>"
                    class="action primary buy-now"
                    id="product-buy-now-button">
                <span><?= $block->escapeHtml(__('Buy Now')) ?></span>
            </button>
            <div class="cc-pdp-wishlist">
                <?= $block->getChildHtml('view.addto.wishlist.cart') ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        },
        "body.catalog-product-view": {
            "js/pdp-figma": {}
        }
    }
</script>
