<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/* @var $block \Magento\Catalog\Block\Product\View\Options */
?>

<?php $_options = $block->decorateArray($block->getOptions()) ?>
<?php $_productId = $block->getProduct()->getId() ?>
<?php if (count($_options)) :?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceOptions": {
                "optionConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                "controlContainer": ".field",
                "priceHolderSelector": "[data-product-id='<?= $block->escapeHtml($_productId) ?>'][data-role=priceBox]"
            }
        }
    }
</script>
    <?php foreach ($_options as $_option) :?>
        <?= $block->getOptionHtml($_option) ?>
    <?php endforeach; ?>
<?php endif; ?>

<div id="AdvancePayment" class="protabox1">
    <div class="advancepaymnt01">
        <h3>ADVANCE PAYMENT <div class="protabclose1 AdvancePayment_close">X</div></h3>
        <p>As this order will be custom made only for you, 50% advance Payment is mandatory to place your order. You can make this payment using our Payment Gateway. We accept payments through Visa, MasterCard, AmEx, Debit Cards and Netbanking. For more details, please check the payment terms on this page below</p>
    </div>
</div>

<style>
#AdvancePayment{
    -webkit-transform: scale(0.8);
       -moz-transform: scale(0.8);
        -ms-transform: scale(0.8);
            transform: scale(0.8);
}
.popup_visible #AdvancePayment {
    -webkit-transform: scale(1);
       -moz-transform: scale(1);
        -ms-transform: scale(1);
            transform: scale(1);
}
#tCard{
    -webkit-transform: scale(0.8);
       -moz-transform: scale(0.8);
        -ms-transform: scale(0.8);
            transform: scale(0.8);
}
.popup_visible #tCard {
    -webkit-transform: scale(1);
       -moz-transform: scale(1);
        -ms-transform: scale(1);
            transform: scale(1);
}
</style>
